version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    env_file:
      - .env
    expose:
      - 3306
      - 33060
  backend:
    build: backend
    restart: always
    volumes:
      - ./backend:/code
    env_file:
      - .env
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
    depends_on:
     - db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - backnet
    environment:
      - PMA_ARBITRARY=0
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
      - frontnet
volumes:
  db-data:
networks:
  backnet:
  frontnet:
